#variables declaration here
variable "red_vpc" {}
variable "white_vpc" {}
variable "red_vpc_cidr_block" {}
variable "white_vpc_cidr_block" {}
variable "red_subnet_cidr_block" {}
variable "white_subnet_cidr_block" {}
variable "red_subnet_az" {}
variable "white_subnet_az" {}
variable "white_ubuntu_ami_id" {}
variable "red_rhel_ami_id" {}
