pipeline {
  agent any

  environment {
    PROJECT_ID = "mystic-centaur-297207"
  }

  stages {

    stage('Clone Repo') {
      steps {
        git branch: 'tf-gcp',
            url: 'https://github.com/vamsikrishna2049/terraform.git'
      }
    }

    stage('Authenticate (WIF)') {
      steps {
        sh 'echo "Using Workload Identity Federation (OIDC)"'
      }
    }

    stage('Terraform') {
      steps {
        dir('gcp-Jenkins/infra') {   
          sh 'terraform init'
          sh 'terraform plan'
          sh 'terraform apply'
        }
      }
    }

  }
}
