pipeline {
    agent any

    environment {
        PROJECT_ID = "mystic-centaur-297207"
        TF_IN_AUTOMATION = "true"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'tf-gcp', url: 'https://github.com/vamsikrishna2049/terraform.git'
            }
        }

        stage('Authenticate to GCP (WIF)') {
            steps {
                sh '''
                echo "Authenticating via Workload Identity Federation..."

                # This assumes Jenkins is configured with OIDC
                gcloud auth login --brief || true

                export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token)
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh 'terraform plan -var-file=terraform.tfvars'
            }
        }

        stage('Manual Approval') {
            steps {
                input message: 'Approve Terraform Apply?'
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'terraform apply -auto-approve -var-file=terraform.tfvars'
            }
        }
    }
}
