pipeline {
    agent any

    environment {
        TF_IN_AUTOMATION = "true"
        GOOGLE_APPLICATION_CREDENTIALS = credentials('gcp-sa-key')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'tf-gcp',
                    url: 'https://github.com/vamsikrishna2049/terraform.git'
            }
        }

        stage('Authenticate to GCP (WIF)') {
            steps {
                sh '''
                    echo "Using Workload Identity Federation via ADC..."
                    gcloud auth application-default print-access-token
                '''
            }
        }

        stage('Init') {
            steps {
                sh 'terraform init -upgrade'
            }
        }

        stage('Validate') {
            steps {
                sh 'terraform validate'
            }
        }

        stage('Plan') {
            steps {
                sh 'terraform plan -var-file=terraform.tfvars'
            }
        }

        stage('Approval') {
            steps {
                input message: 'Approve Apply?'
            }
        }

        stage('Apply') {
            steps {
                sh 'terraform apply -auto-approve -var-file=terraform.tfvars'
            }
        }
    }
}
