# #variables declaration here
# variable "vpc_name" {}
# variable "vpc_cidr_block" {}
# variable "pub_subnet_count" {}
# variable "pub_subnet_cidr_block" {}
# variable "pvt_subnet_count" {}
# variable "pvt_subnet_cidr_block" {}
# variable "azs" {}
# variable "IGW_name" {}
# variable "key_name" {}
# variable "Main_Routing_Table" {}
# variable "ami_id" {}